spring.application.name=expiry-manager

# Mailtrapの設定
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=b95ab934925586
spring.mail.password=2530d1fb71ab1c
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
